#!/bin/sh

compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-ca.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-ca.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-ca.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-ca.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-ca.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-ca.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-cs.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-cs.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-cs.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-cs.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-cs.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-cs.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-cy.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-cy.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-cy.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-cy.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-cy.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-cy.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-da.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-da.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-da.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-da.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-da.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-da.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-de.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-de.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-de.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-de.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-de.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-de.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-en-US.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-en-US.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-en-US.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-en-US.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-en-US.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-en-US.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-es.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-es.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-es.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-es.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-es.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-es.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-es-CL.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-es-CL.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-es-CL.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-es-CL.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-es-CL.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-es-CL.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-et.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-et.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-et.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-et.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-et.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-et.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-eu.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-eu.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-eu.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-eu.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-eu.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-eu.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-fr.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-fr.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-fr.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-fr.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-fr.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-fr.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-fy.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-fy.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-fy.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-fy.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-fy.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-fy.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-he.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-he.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-he.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-he.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-he.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-he.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-hu.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-hu.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-hu.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-hu.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-hu.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-hu.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-id.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-id.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-id.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-id.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-id.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-id.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-it.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-it.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-it.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-it.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-it.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-it.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-ja.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-ja.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-ja.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-ja.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-ja.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-ja.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-ko.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-ko.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-ko.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-ko.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-ko.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-ko.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-lt.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-lt.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-lt.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-lt.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-lt.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-lt.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-nb-NO.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-nb-NO.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-nb-NO.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-nb-NO.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-nb-NO.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-nb-NO.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-nl.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-nl.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-nl.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-nl.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-nl.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-nl.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-pa.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-pa.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-pa.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-pa.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-pa.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-pa.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-pl.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-pl.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-pl.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-pl.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-pl.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-pl.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-pt.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-pt.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-pt.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-pt.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-pt.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-pt.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-pt-BR.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-pt-BR.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-pt-BR.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-pt-BR.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-pt-BR.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-pt-BR.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-rm.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-rm.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-rm.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-rm.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-rm.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-rm.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-ru.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-ru.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-ru.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-ru.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-ru.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-ru.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-sk.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-sk.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-sk.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-sk.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-sk.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-sk.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-sl.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-sl.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-sl.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-sl.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-sl.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-sl.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-sq.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-sq.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-sq.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-sq.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-sq.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-sq.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-sr.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-sr.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-sr.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-sr.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-sr.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-sr.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-sr-LATN.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-sr-LATN.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-sr-LATN.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-sr-LATN.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-sr-LATN.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-sr-LATN.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-sv.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-sv.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-sv.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-sv.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-sv.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-sv.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-tr.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-tr.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-tr.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-tr.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-tr.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-tr.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-zh-CN.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-zh-CN.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-zh-CN.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-zh-CN.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-zh-CN.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-zh-CN.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-zh-TW.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-zh-TW.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-zh-TW.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-zh-TW.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-zh-TW.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-zh-TW.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signin-xx.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signin-xx.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signin-xx.png
compare -metric PSNR /home/ubuntu/pub/fxa-phantom/dev/$now/fxa-signup-xx.png /home/ubuntu/pub/fxa-phantom/prod/$now/fxa-signup-xx.png /home/ubuntu/pub/fxa-phantom/dev-prod/$now/fxa-signup-xx.png
