#!/bin/sh

node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js ca
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js cs
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js cy
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js da
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js de
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js en-US
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js es
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js es-CL
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js et
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js eu
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js fr
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js fy
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js he
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js hu
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js id
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js it
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js ja
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js ko
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js lt
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js nb-NO
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js nl
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js pa
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js pl
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js pt
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js pt-BR
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js rm
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js ru
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js sk
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js sl
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js sq
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js sr
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js sr-LATN
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js sv
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js tr
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js zh-CN
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js zh-TW
node_modules/phantomjs/bin/phantomjs fxa-l18n/page-scrape/loadPage.js xx
