#!/bin/sh
bin/phantomjs loadPage.js en-US
bin/phantomjs loadPage.js ca
bin/phantomjs loadPage.js cs
bin/phantomjs loadPage.js cy
bin/phantomjs loadPage.js de
bin/phantomjs loadPage.js es
bin/phantomjs loadPage.js fr
bin/phantomjs loadPage.js fy
bin/phantomjs loadPage.js he
bin/phantomjs loadPage.js hu
bin/phantomjs loadPage.js id
bin/phantomjs loadPage.js it
bin/phantomjs loadPage.js ko
bin/phantomjs loadPage.js lt
bin/phantomjs loadPage.js nb-NO
bin/phantomjs loadPage.js nl
bin/phantomjs loadPage.js pa
bin/phantomjs loadPage.js pl
bin/phantomjs loadPage.js pt-BR
bin/phantomjs loadPage.js rm
bin/phantomjs loadPage.js ru
bin/phantomjs loadPage.js sk
bin/phantomjs loadPage.js sq
bin/phantomjs loadPage.js sr
bin/phantomjs loadPage.js sr-LATN
bin/phantomjs loadPage.js sv
bin/phantomjs loadPage.js tr
bin/phantomjs loadPage.js zh-CN
bin/phantomjs loadPage.js zh-TW
