./getRestmailText cs@restmail.net
./getRestmailText cy@restmail.net
./getRestmailText de@restmail.net
./getRestmailText es@restmail.net
./getRestmailText fr@restmail.net
./getRestmailText fy@restmail.net
./getRestmailText hu@restmail.net
./getRestmailText it@restmail.net
./getRestmailText ko@restmail.net
./getRestmailText lt@restmail.net
./getRestmailText nb-NO@restmail.net
./getRestmailText nl@restmail.net
./getRestmailText pl@restmail.net
./getRestmailText pt-BR@restmail.net
./getRestmailText rm@restmail.net
./getRestmailText ru@restmail.net
./getRestmailText sk@restmail.net
./getRestmailText sq@restmail.net
./getRestmailText sr@restmail.net
./getRestmailText sr-LATN@restmail.net
./getRestmailText sv@restmail.net
./getRestmailText zh-CN@restmail.net
./getRestmailText zh-TW@restmail.net
